/* Generated by Yosys 0.67+post (git sha1 22c15a7ecd53437f18f67c72572bd693f78357ca, GNU /usr/bin/g++ 16.1.1) */

module incomp_if(i0, i1, i2, y);
  input i0;
  wire i0;
  input i1;
  wire i1;
  input i2;
  wire i2;
  output y;
  reg y;
  always @*
    if (i0) y = i1;
endmodule
