/* Generated by Yosys 0.67+post (git sha1 22c15a7ecd53437f18f67c72572bd693f78357ca, GNU /usr/bin/g++ 16.1.1) */

module comp_case(i0, i1, i2, sel, y);
  input i0;
  wire i0;
  input i1;
  wire i1;
  input i2;
  wire i2;
  input [1:0] sel;
  wire [1:0] sel;
  output y;
  wire y;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  sky130_fd_sc_hd__mux2i_1 _09_ (
    .A0(_01_),
    .A1(_02_),
    .S(_06_),
    .Y(_04_)
  );
  sky130_fd_sc_hd__nand2_1 _10_ (
    .A(_03_),
    .B(_07_),
    .Y(_05_)
  );
  sky130_fd_sc_hd__o21ai_0 _11_ (
    .A1(_07_),
    .A2(_04_),
    .B1(_05_),
    .Y(_08_)
  );
  assign _01_ = i0;
  assign _02_ = i1;
  assign _06_ = sel[0];
  assign _03_ = i2;
  assign _07_ = sel[1];
  assign y = _08_;
endmodule
