/* Generated by Yosys 0.67+post (git sha1 22c15a7ecd53437f18f67c72572bd693f78357ca, GNU /usr/bin/g++ 16.1.1) */

(* top =  1  *)
(* src = "multiple_module_opt.v:11.1-21.10" *)
module multiple_module_opt(a, b, c, d, y);
  (* src = "multiple_module_opt.v:11.34-11.35" *)
  input a;
  wire a;
  (* src = "multiple_module_opt.v:11.44-11.45" *)
  input b;
  wire b;
  (* src = "multiple_module_opt.v:11.54-11.55" *)
  input c;
  wire c;
  (* src = "multiple_module_opt.v:11.64-11.65" *)
  input d;
  wire d;
  (* src = "multiple_module_opt.v:11.75-11.76" *)
  output y;
  wire y;
  wire _0_;
  (* src = "multiple_module_opt.v:11.34-11.35" *)
  wire _1_;
  (* src = "multiple_module_opt.v:11.44-11.45" *)
  wire _2_;
  (* src = "multiple_module_opt.v:11.54-11.55" *)
  wire _3_;
  (* src = "multiple_module_opt.v:11.75-11.76" *)
  wire _4_;
  (* hdlname = "U1 a" *)
  (* src = "multiple_module_opt.v:1.26-1.27" *)
  wire \U1.a ;
  (* hdlname = "U1 b" *)
  (* src = "multiple_module_opt.v:1.36-1.37" *)
  wire \U1.b ;
  (* hdlname = "U1 y" *)
  (* src = "multiple_module_opt.v:1.47-1.48" *)
  wire \U1.y ;
  (* src = "multiple_module_opt.v:12.6-12.8" *)
  wire n1;
  sky130_fd_sc_hd__a21o_1 _5_ (
    .A1(_2_),
    .A2(_1_),
    .B1(_3_),
    .X(_4_)
  );
  assign n1 = \U1.y ;
  assign \U1.b  = 1'h1;
  assign \U1.a  = a;
  assign _2_ = b;
  assign _3_ = c;
  assign y = _4_;
  assign _1_ = a;
endmodule
