/* Generated by Yosys 0.67+post (git sha1 22c15a7ecd53437f18f67c72572bd693f78357ca, GNU /usr/bin/g++ 16.1.1) */

module dff_asyncres_syncres(clk, async_reset, sync_reset, d, q);
  input clk;
  wire clk;
  input async_reset;
  wire async_reset;
  input sync_reset;
  wire sync_reset;
  input d;
  wire d;
  output q;
  wire q;
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire _4_;
  wire _5_;
  wire _6_;
  sky130_fd_sc_hd__clkinv_1 _7_ (
    .A(_2_),
    .Y(_3_)
  );
  sky130_fd_sc_hd__nor2b_1 _8_ (
    .A(_5_),
    .B_N(_4_),
    .Y(_1_)
  );
  sky130_fd_sc_hd__dfrtp_1 _9_ (
    .CLK(clk),
    .D(_0_),
    .Q(q),
    .RESET_B(_6_)
  );
  assign _4_ = d;
  assign _5_ = sync_reset;
  assign _0_ = _1_;
  assign _2_ = async_reset;
  assign _6_ = _3_;
endmodule
