/* Generated by Yosys 0.67+post (git sha1 22c15a7ecd53437f18f67c72572bd693f78357ca, GNU /usr/bin/g++ 16.1.1) */

(* top =  1  *)
(* src = "partial_case_assign.v:1.1-16.10" *)
module partial_case_assign(i0, i1, i2, sel, y, x);
  (* src = "partial_case_assign.v:1.35-1.37" *)
  input i0;
  wire i0;
  (* src = "partial_case_assign.v:1.46-1.48" *)
  input i1;
  wire i1;
  (* src = "partial_case_assign.v:1.57-1.59" *)
  input i2;
  wire i2;
  (* src = "partial_case_assign.v:1.74-1.77" *)
  input [1:0] sel;
  wire [1:0] sel;
  (* src = "partial_case_assign.v:1.90-1.91" *)
  output y;
  wire y;
  (* src = "partial_case_assign.v:1.105-1.106" *)
  output x;
  reg x;
  (* src = "partial_case_assign.v:2.1-15.4" *)
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  (* src = "partial_case_assign.v:2.1-15.4" *)
  wire _07_;
  wire _08_;
  (* src = "partial_case_assign.v:1.35-1.37" *)
  wire _09_;
  (* src = "partial_case_assign.v:1.46-1.48" *)
  wire _10_;
  (* src = "partial_case_assign.v:1.57-1.59" *)
  wire _11_;
  wire _12_;
  wire _13_;
  (* src = "partial_case_assign.v:1.74-1.77" *)
  wire _14_;
  (* src = "partial_case_assign.v:1.74-1.77" *)
  wire _15_;
  (* src = "partial_case_assign.v:1.90-1.91" *)
  wire _16_;
  sky130_fd_sc_hd__nor2b_1 _17_ (
    .A(_15_),
    .B_N(_14_),
    .Y(_08_)
  );
  sky130_fd_sc_hd__and2_0 _18_ (
    .A(_15_),
    .B(_11_),
    .X(_12_)
  );
  sky130_fd_sc_hd__nor2_1 _19_ (
    .A(_14_),
    .B(_15_),
    .Y(_13_)
  );
  sky130_fd_sc_hd__a221o_1 _20_ (
    .A1(_10_),
    .A2(_08_),
    .B1(_13_),
    .B2(_09_),
    .C1(_12_),
    .X(_16_)
  );
  sky130_fd_sc_hd__mux2_1 _21_ (
    .A0(_10_),
    .A1(_11_),
    .S(_13_),
    .X(_07_)
  );
  (* src = "partial_case_assign.v:2.1-15.4" *)
  always @*
    if (!_01_) x = _00_;
  assign _14_ = sel[0];
  assign _15_ = sel[1];
  assign _01_ = _08_;
  assign _10_ = i1;
  assign _11_ = i2;
  assign _09_ = i0;
  assign y = _16_;
  assign _00_ = _07_;
endmodule
