/* Generated by Yosys 0.67+post (git sha1 22c15a7ecd53437f18f67c72572bd693f78357ca, GNU /usr/bin/g++ 16.1.1) */

(* top =  1  *)
(* src = "multiple_module_opt.v:11.1-21.10" *)
module multiple_module_opt(a, b, c, d, y);
  (* src = "multiple_module_opt.v:11.34-11.35" *)
  input a;
  wire a;
  (* src = "multiple_module_opt.v:11.44-11.45" *)
  input b;
  wire b;
  (* src = "multiple_module_opt.v:11.54-11.55" *)
  input c;
  wire c;
  (* src = "multiple_module_opt.v:11.64-11.65" *)
  input d;
  wire d;
  (* src = "multiple_module_opt.v:11.75-11.76" *)
  output y;
  wire y;
  wire _0_;
  (* src = "multiple_module_opt.v:11.44-11.45" *)
  wire _1_;
  (* src = "multiple_module_opt.v:11.54-11.55" *)
  wire _2_;
  (* src = "multiple_module_opt.v:12.6-12.8" *)
  wire _3_;
  (* src = "multiple_module_opt.v:11.75-11.76" *)
  wire _4_;
  (* src = "multiple_module_opt.v:12.6-12.8" *)
  wire n1;
  sky130_fd_sc_hd__a21o_1 _5_ (
    .A1(_1_),
    .A2(_3_),
    .B1(_2_),
    .X(_4_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "multiple_module_opt.v:14.13-14.43" *)
  sub_module1 U1 (
    .a(a),
    .b(1'h1),
    .y(n1)
  );
  assign _1_ = b;
  assign _3_ = n1;
  assign _2_ = c;
  assign y = _4_;
endmodule

(* src = "multiple_module_opt.v:1.1-3.10" *)
module sub_module1(a, b, y);
  (* src = "multiple_module_opt.v:1.26-1.27" *)
  input a;
  wire a;
  (* src = "multiple_module_opt.v:1.36-1.37" *)
  input b;
  wire b;
  (* src = "multiple_module_opt.v:1.47-1.48" *)
  output y;
  wire y;
  (* src = "multiple_module_opt.v:1.26-1.27" *)
  wire _0_;
  (* src = "multiple_module_opt.v:1.36-1.37" *)
  wire _1_;
  (* src = "multiple_module_opt.v:1.47-1.48" *)
  wire _2_;
  sky130_fd_sc_hd__and2_0 _3_ (
    .A(_0_),
    .B(_1_),
    .X(_2_)
  );
  assign _0_ = a;
  assign _1_ = b;
  assign y = _2_;
endmodule
