/* Generated by Yosys 0.67+post (git sha1 22c15a7ecd53437f18f67c72572bd693f78357ca, GNU /usr/bin/g++ 16.1.1) */

module bad_case(i0, i1, i2, i3, sel, y);
  input i0;
  wire i0;
  input i1;
  wire i1;
  input i2;
  wire i2;
  input i3;
  wire i3;
  input [1:0] sel;
  wire [1:0] sel;
  output y;
  reg y;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  sky130_fd_sc_hd__clkinv_1 _21_ (
    .A(_11_),
    .Y(_18_)
  );
  sky130_fd_sc_hd__and2_0 _22_ (
    .A(_19_),
    .B(_20_),
    .X(_10_)
  );
  sky130_fd_sc_hd__nor2b_1 _23_ (
    .A(_19_),
    .B_N(_20_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__nor2b_1 _24_ (
    .A(_20_),
    .B_N(_19_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__nand3b_1 _25_ (
    .A_N(_20_),
    .B(_12_),
    .C(_19_),
    .Y(_16_)
  );
  sky130_fd_sc_hd__nand3b_1 _26_ (
    .A_N(_19_),
    .B(_20_),
    .C(_13_),
    .Y(_17_)
  );
  sky130_fd_sc_hd__o311ai_0 _27_ (
    .A1(_18_),
    .A2(_14_),
    .A3(_15_),
    .B1(_16_),
    .C1(_17_),
    .Y(_09_)
  );
  always @*
    if (!_01_) y = _00_;
  assign _19_ = sel[0];
  assign _20_ = sel[1];
  assign _01_ = _10_;
  assign _11_ = i0;
  assign _12_ = i1;
  assign _13_ = i2;
  assign _00_ = _09_;
endmodule
