/* Generated by Yosys 0.67+post (git sha1 22c15a7ecd53437f18f67c72572bd693f78357ca, GNU /usr/bin/g++ 16.1.1) */

module dff_async_set(clk, async_set, d, q);
  input clk;
  wire clk;
  input async_set;
  wire async_set;
  input d;
  wire d;
  output q;
  wire q;
  wire _0_;
  wire _1_;
  wire _2_;
  sky130_fd_sc_hd__clkinv_1 _3_ (
    .A(_0_),
    .Y(_1_)
  );
  sky130_fd_sc_hd__dfstp_2 _4_ (
    .CLK(clk),
    .D(d),
    .Q(q),
    .SET_B(_2_)
  );
  assign _0_ = async_set;
  assign _2_ = _1_;
endmodule
