/* Generated by Yosys 0.67+post (git sha1 22c15a7ecd53437f18f67c72572bd693f78357ca, GNU /usr/bin/g++ 16.1.1) */

module opt_check3(a, b, c, y);
  input a;
  wire a;
  input b;
  wire b;
  input c;
  wire c;
  output y;
  wire y;
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire _4_;
  sky130_fd_sc_hd__and3_1 _5_ (
    .A(_3_),
    .B(_2_),
    .C(_1_),
    .X(_4_)
  );
  assign _3_ = c;
  assign _2_ = b;
  assign _1_ = a;
  assign y = _4_;
endmodule
