/* Generated by Yosys 0.67+post (git sha1 22c15a7ecd53437f18f67c72572bd693f78357ca, GNU /usr/bin/g++ 16.1.1) */

(* top =  1  *)
(* src = "dff_const1.v:1.1-10.10" *)
module dff_const1(clk, reset, q);
  (* src = "dff_const1.v:1.25-1.28" *)
  input clk;
  wire clk;
  (* src = "dff_const1.v:1.36-1.41" *)
  input reset;
  wire reset;
  (* src = "dff_const1.v:1.54-1.55" *)
  output q;
  wire q;
  wire _0_;
  (* src = "dff_const1.v:1.36-1.41" *)
  wire _1_;
  wire _2_;
  sky130_fd_sc_hd__clkinv_1 _3_ (
    .A(_1_),
    .Y(_0_)
  );
  (* src = "dff_const1.v:2.1-8.4" *)
  sky130_fd_sc_hd__dfrtp_1 _4_ (
    .CLK(clk),
    .D(1'h1),
    .Q(q),
    .RESET_B(_2_)
  );
  assign _1_ = reset;
  assign _2_ = _0_;
endmodule
