/* Generated by Yosys 0.67+post (git sha1 22c15a7ecd53437f18f67c72572bd693f78357ca, GNU /usr/bin/g++ 16.1.1) */

module incomp_case(i0, i1, i2, sel, y);
  input i0;
  wire i0;
  input i1;
  wire i1;
  input i2;
  wire i2;
  input [1:0] sel;
  wire [1:0] sel;
  output y;
  reg y;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  sky130_fd_sc_hd__nand2b_1 _08_ (
    .A_N(_07_),
    .B(_06_),
    .Y(_05_)
  );
  sky130_fd_sc_hd__mux2_1 _09_ (
    .A0(_04_),
    .A1(_03_),
    .S(_05_),
    .X(_02_)
  );
  always @*
    if (!sel[1]) y = _00_;
  assign _07_ = sel[1];
  assign _06_ = sel[0];
  assign _04_ = i1;
  assign _03_ = i0;
  assign _00_ = _02_;
endmodule
