/* Generated by Yosys 0.67+post (git sha1 22c15a7ecd53437f18f67c72572bd693f78357ca, GNU /usr/bin/g++ 16.1.1) */

module dff_const2(clk, reset, q);
  input clk;
  wire clk;
  input reset;
  wire reset;
  output q;
  wire q;
  assign q = 1'h1;
endmodule
