/* Generated by Yosys 0.67+post (git sha1 22c15a7ecd53437f18f67c72572bd693f78357ca, GNU /usr/bin/g++ 16.1.1) */

module blocking_caveat(a, b, c, d);
  input a;
  wire a;
  input b;
  wire b;
  input c;
  wire c;
  output d;
  wire d;
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire _4_;
  sky130_fd_sc_hd__o21a_1 _5_ (
    .A1(_1_),
    .A2(_2_),
    .B1(_3_),
    .X(_4_)
  );
  assign _1_ = a;
  assign _2_ = b;
  assign _3_ = c;
  assign d = _4_;
endmodule
