/* Generated by Yosys 0.67+post (git sha1 22c15a7ecd53437f18f67c72572bd693f78357ca, GNU /usr/bin/g++ 16.1.1) */

module dff_syncres(clk, async_reset, sync_reset, d, q);
  input clk;
  wire clk;
  input async_reset;
  wire async_reset;
  input sync_reset;
  wire sync_reset;
  input d;
  wire d;
  output q;
  wire q;
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  sky130_fd_sc_hd__nor2b_1 _4_ (
    .A(_2_),
    .B_N(_1_),
    .Y(_0_)
  );
  sky130_fd_sc_hd__dfxtp_1 _5_ (
    .CLK(clk),
    .D(_3_),
    .Q(q)
  );
  assign _1_ = d;
  assign _2_ = sync_reset;
  assign _3_ = _0_;
endmodule
